services:
  mongo:
    image: mongo:7
    container_name: tirgo_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: tirgo
      TIRGO_DB_PASSWORD: ${TIRGO_DB_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    # Lo exponemos solo en localhost para que tu contenedor (modo host) lo vea
    ports:
      - "127.0.0.1:27017:27017"

  mongo-express:
    image: mongo-express:1.0.2
    container_name: tirgo_mongo_express
    restart: unless-stopped
    depends_on: [mongo]
    environment:
      # Conexión directa usando el admin
      ME_CONFIG_MONGODB_URL: "mongodb://admin:${MONGO_ROOT_PASSWORD}@mongo:27017/?authSource=admin"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

      # (Opcional) proteger la web con usuario/contraseña propia de la consola:
      ME_CONFIG_BASICAUTH_USERNAME: "TirgoAdmin"
      ME_CONFIG_BASICAUTH_PASSWORD: "tirgo"

    ports:
      - "127.0.0.1:8081:8081"

volumes:
  mongo_data:
